before_script:
  - chcp 65001

stages:
  - build
  - test
  - push

build:
  stage: build
  script:
    - ".\\build.bat"

test:
  stage: test
  script:
    - ".\\test.bat"

push:
  stage: push
  only:
   - master
  script:
    - ".\\pack.bat"
    - ".\\push.bat"
