before_script:
  - chcp 65001

stages:
  - build
  - test
  - push

build-debug:
  stage: build
  script:
    - ".\\build-debug.ps1"

build:
  stage: build
  script:
    - ".\\build.ps1"

test-debug:
  stage: test
  script:
    - ".\\test-debug.ps1"

test:
  stage: test
  script:
    - ".\\test.ps1"
    
push-debug:
  stage: push
  only:
    - dev
  script:
    - ".\\pack-debug.ps1"
    - ".\\push-debug.ps1"
  artifacts:
    paths:
      - "Src\\*\\bin\\Debug\\"
    expire_in: 30d

push:
  stage: push
  only:
   - master
  script:
    - ".\\pack.ps1"
    - ".\\push.ps1"
  artifacts:
    paths:
      - "Src\\*\\bin\\Release\\"
    expire_in: 30d
    