before_script:
  - chcp 65001

stages:
  - build
  - test
  - push

build:
  stage: build
  script:
    - ".\\build.bat"
  artifacts:
    paths:
      - "Src\\*\\bin\\Release\\"
    expire_in: 1h

test:
  stage: test
  script:
    - ".\\test.bat"
    
push-debug:
  stage: push
  only:
    - dev
  script:
    - ".\\pack-debug.bat"
    - ".\\push-debug.bat"

push:
  stage: push
  only:
   - master
  script:
    - ".\\pack.bat"
    - ".\\push.bat"
    