rd /s /q Lsj.Util\obj
rd /s /q Lsj.Util.CsBuilder\obj
rd /s /q Lsj.Util.Data\obj
rd /s /q Lsj.Util.Debugger\obj
rd /s /q Lsj.Util.HtmlBuilder\obj
rd /s /q Lsj.Util.Net\obj
rd /s /q Lsj.Util.Net.Web\obj
rd /s /q Lsj.Util.Office\obj
rd /s /q Lsj.Util.Protobuf\obj
rd /s /q Lsj.Util.SQLBuilder\obj