using Lsj.Util.Win32.BaseTypes;
using Lsj.Util.Win32.Enums;
using System.Runtime.InteropServices;

namespace Lsj.Util.Win32.Structs
{
    /// <summary>
    /// <para>
    /// Contains information about a simulated message generated by an input device other than a keyboard or mouse.
    /// </para>
    /// <para>
    /// From: <see href="https://docs.microsoft.com/zh-cn/windows/win32/api/winuser/ns-winuser-hardwareinput"/>
    /// </para>
    /// </summary>
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct HARDWAREINPUT
    {
        /// <summary>
        /// The message generated by the input hardware.
        /// </summary>
        public WindowMessages uMsg;

        /// <summary>
        /// The low-order word of the <see cref="MSG.lParam"/> parameter for <see cref="uMsg"/>.
        /// </summary>
        public WORD wParamL;

        /// <summary>
        /// The high-order word of the <see cref="MSG.lParam"/> parameter for <see cref="uMsg"/>.
        /// </summary>
        public WORD wParamH;
    }
}
