using Lsj.Util.Win32.BaseTypes;
using Lsj.Util.Win32.Enums;
using System.Runtime.InteropServices;
using static Lsj.Util.Win32.Enums.JOBOBJECTINFOCLASS;
using static Lsj.Util.Win32.Kernel32;

namespace Lsj.Util.Win32.Structs
{
    /// <summary>
    /// <para>
    /// Contains information used to control the network traffic for a job.
    /// This structure is used by the <see cref="SetInformationJobObject"/> and <see cref="QueryInformationJobObject"/> functions
    /// with the <see cref="JobObjectNetRateControlInformation"/> information class.
    /// </para>
    /// <para>
    /// From: <see href="https://docs.microsoft.com/zh-cn/windows/win32/api/winnt/ns-winnt-jobobject_net_rate_control_information"/>
    /// </para>
    /// </summary>
    /// <remarks>
    /// You can only set the control of the network traffic on one job in a hierarchy of nested jobs.
    /// The settings that you specify apply to that job and the child jobs in the hierarchy for that job.
    /// The settings do not apply to the chain of jobs from the parent job up to the top of the hierarchy.
    /// You can change the settings on the original job in the hierarchy on which you set rate control.
    /// However, attempts to set values for the control of the network rate for any other jobs in the hierarchy, including the parent jobs, fail.
    /// </remarks>
    [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Unicode)]
    public struct JOBOBJECT_NET_RATE_CONTROL_INFORMATION
    {
        /// <summary>
        /// The maximum bandwidth for outgoing network traffic for the job, in bytes.
        /// </summary>
        public DWORD64 MaxBandwidth;

        /// <summary>
        /// A combination of <see cref="JOB_OBJECT_NET_RATE_CONTROL_FLAGS"/> enumeration values that specify the scheduling policy for network rate control.
        /// </summary>
        public JOB_OBJECT_NET_RATE_CONTROL_FLAGS ControlFlags;

        /// <summary>
        /// The value to use for the Differentiated Service code point (DSCP) field to turn on network quality of service (QoS)
        /// for all outgoing network traffic generated by the processes of the job object.
        /// The valid range is from 0x00 through 0x3F. For information about DSCP, see Differentiated Services.
        /// </summary>
        public BYTE DscpTag;
    }
}
