namespace Lsj.Util.Win32.Enums
{
    /// <summary>
    /// PROCESS_CREATION_MITIGATION_POLICY
    /// </summary>
    public enum PROCESS_CREATION_MITIGATION_POLICY : ulong
    {
        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_DEP_ENABLE
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_DEP_ENABLE = 0x01,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_DEP_ATL_THUNK_ENABLE
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_DEP_ATL_THUNK_ENABLE = 0x02,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_SEHOP_ENABLE
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_SEHOP_ENABLE = 0x04,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_MASK = 0x00000003 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_DEFER = 0x00000000 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON = 0x00000001 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_OFF = 0x00000002 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON_REQ_RELOCS
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FORCE_RELOCATE_IMAGES_ALWAYS_ON_REQ_RELOCS = 0x00000003 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_MASK = 0x00000003 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_DEFER = 0x00000000 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_ON = 0x00000001 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_ALWAYS_OFF = 0x00000002 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HEAP_TERMINATE_RESERVED = 0x00000003 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_MASK = 0x00000003 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_DEFER = 0x00000000 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_ON = 0x00000001 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_ALWAYS_OFF = 0x00000002 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BOTTOM_UP_ASLR_RESERVED = 0x00000003 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_MASK = 0x00000003 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_DEFER = 0x00000000 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_ON = 0x00000001 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_ALWAYS_OFF = 0x00000002 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_HIGH_ENTROPY_ASLR_RESERVED = 0x00000003 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_MASK = 0x00000003 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_DEFER = 0x00000000 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_ON = 0x00000001 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_ALWAYS_OFF = 0x00000002 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_STRICT_HANDLE_CHECKS_RESERVED = 0x00000003 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_MASK = 0x00000003 << 28,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_DEFER = 0x00000000 << 28,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_ALWAYS_ON = 0x00000001 << 28,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_ALWAYS_OFF = 0x00000002 << 28,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_WIN32K_SYSTEM_CALL_DISABLE_RESERVED = 0x00000003 << 28,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_MASK = 0x00000003 << 32,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_DEFER = 0x00000000 << 32,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_ON = 0x00000001 << 32,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_ALWAYS_OFF = 0x00000002 << 32,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_EXTENSION_POINT_DISABLE_RESERVED = 0x00000003 << 32,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_MASK = 0x00000003 << 36,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_DEFER = 0x00000000 << 36,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_ON = 0x00000001 << 36,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_OFF = 0x00000002 << 36,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_ON_ALLOW_OPT_OUT
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_PROHIBIT_DYNAMIC_CODE_ALWAYS_ON_ALLOW_OPT_OUT = 0x00000003 << 36,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_MASK = 0x00000003 << 40,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_DEFER = 0x00000000 << 40,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_ON = 0x00000001 << 40,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_ALWAYS_OFF = 0x00000002 << 40,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_EXPORT_SUPPRESSION
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_CONTROL_FLOW_GUARD_EXPORT_SUPPRESSION = 0x00000003 << 40,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_MASK = 0x00000003 << 44,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_DEFER = 0x00000000 << 44,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_ON = 0x00000001 << 44,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALWAYS_OFF = 0x00000002 << 44,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALLOW_STORE
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_BLOCK_NON_MICROSOFT_BINARIES_ALLOW_STORE = 0x00000003 << 44,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_MASK = 0x00000003 << 48,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_DEFER = 0x00000000 << 48,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_ON = 0x00000001 << 48,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_FONT_DISABLE_ALWAYS_OFF = 0x00000002 << 48,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_AUDIT_NONSYSTEM_FONTS
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_AUDIT_NONSYSTEM_FONTS = 0x00000003 << 48,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_MASK = 0x00000003 << 52,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_DEFER = 0x00000000 << 52,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_ON = 0x00000001 << 52,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_ALWAYS_OFF = 0x00000002 << 52,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_REMOTE_RESERVED = 0x00000003 << 52,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_MASK = 0x00000003 << 56,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_DEFER = 0x00000000 << 56,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_ON = 0x00000001 << 56,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_ALWAYS_OFF = 0x00000002 << 56,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_NO_LOW_LABEL_RESERVED = 0x00000003 << 56,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_MASK = 0x00000003 << 60,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_DEFER = 0x00000000 << 60,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_ON = 0x00000001 << 60,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_ALWAYS_OFF = 0x00000002 << 60,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY_IMAGE_LOAD_PREFER_SYSTEM32_RESERVED = 0x00000003 << 60,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_MASK = 0x00000003 << 4,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_DEFER = 0x00000000 << 4,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_ALWAYS_ON = 0x00000001 << 4,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_ALWAYS_OFF = 0x00000002 << 4,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_AUDIT
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_LOADER_INTEGRITY_CONTINUITY_AUDIT = 0x00000003 << 4,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_MASK = 0x00000003 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_DEFER = 0x00000000 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_ALWAYS_ON = 0x00000001 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_ALWAYS_OFF = 0x00000002 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_STRICT_CONTROL_FLOW_GUARD_RESERVED = 0x00000003 << 8,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_MASK = 0x00000003 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_DEFER = 0x00000000 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_ALWAYS_ON = 0x00000001 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_ALWAYS_OFF = 0x00000002 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_NOINHERIT
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_MODULE_TAMPERING_PROTECTION_NOINHERIT = 0x00000003 << 12,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_MASK = 0x00000003 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_DEFER = 0x00000000 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_ALWAYS_ON = 0x00000001 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_ALWAYS_OFF = 0x00000002 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_RESTRICT_INDIRECT_BRANCH_PREDICTION_RESERVED = 0x00000003 << 16,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_MASK = 0x00000003 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_DEFER = 0x00000000 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_ALWAYS_ON = 0x00000001 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_ALWAYS_OFF = 0x00000002 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_ALLOW_DOWNGRADE_DYNAMIC_CODE_POLICY_RESERVED = 0x00000003 << 20,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_MASK
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_MASK = 0x00000003 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_DEFER
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_DEFER = 0x00000000 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_ALWAYS_ON
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_ALWAYS_ON = 0x00000001 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_ALWAYS_OFF
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_ALWAYS_OFF = 0x00000002 << 24,

        /// <summary>
        /// PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_RESERVED
        /// </summary>
        PROCESS_CREATION_MITIGATION_POLICY2_SPECULATIVE_STORE_BYPASS_DISABLE_RESERVED = 0x00000003 << 24,
    }
}
